### ISSUE TITLE
index error when running mine.py or node.py

### ISSUE THREAD

**Issue by asucrews** [jackschultz/jbc#5]
Hello, i new to python and not 100% where this error is coming from.  I am using python 2.7.14.  Node.py works with out any issue util i try to enable mining.  thank you this project is great and i hope it keeps going.

python mine.py
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly schedul
ed when the scheduler starts
INFO:apscheduler.scheduler:Added job "mine_for_block" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "mine_for_block (trigger: date[20
18-03-23 15:28:18 MST], next run at: 2018-03-23 15:28:18 MST)" (scheduled at 201
8-03-23 15:28:18.538000-07:00)
INFO:apscheduler.scheduler:Removed job mining
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
ERROR:apscheduler.executors.default:Job "mine_for_block (trigger: date[2018-03-2
3 15:28:18 MST], next run at: 2018-03-23 15:28:18 MST)" raised an exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125,
in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mine.py", line 30, in mine_for_block
    prev_block = chain.most_recent_block()
  File "C:\Users\jcrews-adm\jbc\chain.py", line 78, in most_recent_block
    return self.blocks[-1]
IndexError: list index out of range

**Comment by asucrews** [comment]
human error
